Create README.md
codeforlansing/cityzen pull request #2
Opened 2020-08-26 23:56 UTC by RHMason

This is an updated readme.md file for Master that should redirect to the real CityZen docs which are at GitHub pages

2020-08-27 02:14 UTC, egillespie requested changes
@RHMason, the HTML looks correct, but it looks like GitHub's Markdown renderer removes any `meta` HTML attributes. Here's a screenshot of your branch when viewed on GitHub so you can see what I mean:

![image](https://user-images.githubusercontent.com/5572255/91375557-05dd3200-e7e9-11ea-91cc-c6508cfd4eff.png)

With only Markdown at our disposal in `README.md`, there isn't a way to automatically redirect a visitor's browser. I think we should instead update `README.md` to present something a visitor can quickly read and click, like this:

``` md
# Cityzen Documentation

To read the Cityzen documentation, visit [codeforlansing.github.io/cityzen-docs/](https://codeforlansing.github.io/cityzen-docs/).
```

2020-08-27 02:18 UTC, RHMason commented
Eric,

Or should I go the way I originally planned using JavaScript?  Or would
they remove that as well??

Rick

On Wed, Aug 26, 2020 at 10:15 PM Erik Gillespie <notifications@github.com>
wrote:

> *@egillespie* requested changes on this pull request.
>
> @RHMason <https://github.com/RHMason>, the HTML looks correct, but it
> looks like GitHub's Markdown renderer removes any meta HTML attributes.
> Here's a screenshot of your branch when viewed on GitHub so you can see
> what I mean:
>
> [image: image]
> <https://user-images.githubusercontent.com/5572255/91375557-05dd3200-e7e9-11ea-91cc-c6508cfd4eff.png>
>
> With only Markdown at our disposal in README.md, there isn't a way to
> automatically redirect a visitor's browser. I think we should instead
> update README.md to present something a visitor can quickly read and
> click, like this:
>
> # Cityzen Documentation
>
> To read the Cityzen documentation, visit [codeforlansing.github.io/cityzen-docs/](https://codeforlansing.github.io/cityzen-docs/) <http://codeforlansing.github.io/cityzen-docs/%5D(https://codeforlansing.github.io/cityzen-docs/)>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/codeforlansing/cityzen-docs/pull/2#pullrequestreview-476337943>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AA3J2A27JURFEF4AXEPRSPDSCW6SZANCNFSM4QML5GHA>
> .
>

2020-09-01 14:55 UTC, egillespie commented
> Eric, Or should I go the way I originally planned using JavaScript? Or would they remove that as well?? Rick
> […](#)

GitHub will remove the `<script>` tags as well. I think the best approach is to create a link in the `README.md` to the actual documentation website. 😕

2020-09-09 22:38 UTC, egillespie commented
Resolved by #4

2020-09-09 22:38 UTC, closed without merging